### ISSUE TITLE
The json content is not correctly written

### ISSUE THREAD

**Issue by Beatles1692** [MaSch0212/api-test-host#1]
I have tried to post a json file using swagger and I find out two issues : 
first , you should manually create the json folder before you can post your content
sceond , the json file is created but the content is not right . Instead of the correct content , "null" is written.

**Comment by Beatles1692** [comment]
The second issue just happens when we send a json content that is not correctly formatted . The problem is we don't see an error there.

**Comment by MaSch0212** [comment]
Fixed in version 1.0.2
